version: '3'

services:
  api:
    restart: always
    build: ./backend/
    ports:
      - "3554:3554"
    links:
      - mongo
    volumes:
      - ./:/backend
  
  mongo:
    image: mongo
    ports:  
      - "27017:27017"